### ISSUE TITLE
Allow local file source

### ISSUE THREAD

**Issue by RenaKunisaki** [AdAway/AdAway#1010]
I've added `file:///storage/emulated/0/my_hosts` to my hosts sources, but this doesn't seem to work.

**Comment by bart9h** [comment]
@CaptainFrosty this can work, but shouldn't be necessary

**Comment by CaptainFrosty** [comment]
It shouldn't be necessary but it clearly is since AdAway won't recognize anything but http protocol

**Comment by patrickdrd** [comment]
can I do that with es file explorer or solid explorer?
I've already got 2 file managers, I wouldn't want to install another one!

**Comment by CaptainFrosty** [comment]
I think ES can only log into servers not host them, not sure about solid. There are several free apps on the play store that can do them though. just put the hosts files in whatever root directory you designate and add them in AdAway as http://127.0.0.1/whatever.txt

hey petty guy, why are you down voting the truth? this isn't reddit. ADAWAY WILL NOT ACCEPT file:// addresses. you can thumbs down all day and your disapproval isn't going to change that, only an update will. just because you don't feel the need to use local files doesn't mean someone else can't

**Comment by natuschaos** [comment]
Any news on this? We really need a local way to aply hosts from plain text files.

**Comment by CaptainFrosty** [comment]
I've tested it with MiXplorer, it works

**Comment by PerfectSlayer** [comment]
This features is now available. I'm closing the issue.

**Comment by CNote1** [comment]
still not working
