### ISSUE TITLE
How I can remove a Host sources that I don't need anymore ?

### ISSUE THREAD

**Issue by mikhoul** [AdAway/AdAway#1038]
A simple question but I don't see anything to remove a source that I have added I only see that I can "disable" a list (uncheck the box) ? 🤔

I have added a list from https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts only to learn that Adaway don't load list from  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts and I'd like to remove it. 

Since raw.githubusercontent.com is not allowed I suggest that you add a "check" when a user ad an URL that begin with https://raw.githubusercontent.com to warn that the list will not work in Adaway.

Thanks for this marvelous project :octocat:

**Comment by PerfectSlayer** [comment]
If you use a recent version (I can't remember for older ones), long press a source and you will have some controls:
* Edit source URL
* Remove source

About the check, I think it would be better to fix the download issue rather than create an edge case 😅 

If you found the way to remove the source, please close the issue.
And you're welcome 🙏
