### ISSUE TITLE
https webserver

### ISSUE THREAD

**Issue by co5mo** [AdAway/AdAway#1060]
some blocked ads on google news show ugly error can this be fixed using some form of https webserver?

**Comment by PerfectSlayer** [comment]
Do you mind providing more details? Check https://github.com/AdAway/AdAway/blob/master/CONTRIBUTING.md#reporting-bugs 
And a screenshot could also be useful. Thanks!

**Comment by co5mo** [comment]
https://i.imgur.com/Kkbi9Nl.jpg

**Comment by PerfectSlayer** [comment]
Al right, I get it now.
The web server running only serves the port 80 (http).
It should also serve port 443 (https) in order to fix this issue.

But it is definitely a good improvement idea as https should be the norm right now 👍

**Comment by patrickdrd** [comment]
why was it removed from "to do"?

**Comment by PerfectSlayer** [comment]
No idea. Maybe a "project" TODO issue.
I moved in from Development project as it is not planed for the next release.

I already looked at it but the main issue I have is how to issue a valid certificate for the server?
If you have any idea, please share! 😉

**Comment by patrickdrd** [comment]
what do you mean? maybe a local certificate, like the one adguard uses?

**Comment by PerfectSlayer** [comment]
According [the support](https://kb.adguard.com/en/android/overview), AdGuard uses a VPN based solution. To it does not have a web-server.

Here is the problem: in order to serve HTTPS page, I need to have a valid SSL certificate on the server.
So your browser or application will download a blank page from my server without failing due to a certificate issue (cannot get certificate, invalid certificate, etc…).

It's the first step in the _Enabling SSSL_ list: https://cesanta.com/docs/http/ssl.html

**Comment by co5mo** [comment]
any news here?

**Comment by eskhool** [comment]
@PerfectSlayer, as this problem seems to be affecting a limited number of tech savvy users, can we do the following to begin with....Provide a HTTPS server on port 443 and allowing the user to manually upload a SSL cert file and let the user add his own local CA.

We can put a strong disclaimer that this feature is for advanced users only for the moment. 

Am saying this because my problem is also with Google News ugly layout so all it needs is 1 SSL cert for that particular domain (securepubads.g.doubleclick.net) and a local CA cert which I can generate and hence trust. 

Eventually, the bigger solution is for AdAway to dynamically generate the SSL certs and send them to the requesting party but that is a MITM implementation that may be fairly complex to do (compared to 
 the cryptography free hosts replacement that it presently does)

NOTE: The idea of a CA from AdAway is NOT good as it means that anyone with the CA private file can spoof any website. Big security NO-NO

**Comment by eskhool** [comment]
> @PerfectSlayer, as this problem seems to be affecting a limited number of tech savvy users, can we do the following to begin with....Provide a HTTPS server on port 443 and allowing the user to manually upload a SSL cert file and let the user add his own local CA.
> 
> We can put a strong disclaimer that this feature is for advanced users only for the moment.
> 
> Am saying this because my problem is also with Google News ugly layout so all it needs is 1 SSL cert for that particular domain (securepubads.g.doubleclick.net) and a local CA cert which I can generate and hence trust.
> 
> Eventually, the bigger solution is for AdAway to dynamically generate the SSL certs and send them to the requesting party but that is a MITM implementation that may be fairly complex to do (compared to
> the cryptography free hosts replacement that it presently does)
> 
> NOTE: The idea of a CA from AdAway is NOT good as it means that anyone with the CA private file can spoof any website. Big security NO-NO

Effectively, we will need to do half of what is done here. Its in Java so https://crypto.stanford.edu/ssl-mitm/

**Comment by jiteshvassa** [comment]
As others have already mentioned, it would be great if the webserver could cover https and allow for a user generated certificate to be used.

**Comment by PawelSuwinski** [comment]
For now I solved it using mitmproxy on termux:

https://github.com/mitmproxy/mitmproxy#installation
 
       # /data/local/userinit.sh
       PATH+=:/data/data/com.termux/files/home/bin:/data/data/com.termux/files/usr/bin
       HOME=/data
       export PATH HOME
       screen -m -d mitmproxy --listen-host 127.0.0.1 -p 443

**Comment by PerfectSlayer** [comment]
I did a lot of work of this subject the past weeks.
The feature is coming in the next beta 🎉

**Comment by jiteshvassa** [comment]
> I did a lot of work of this subject the past weeks.
> The feature is coming in the next beta

Awesome, thanks for your hard work! 
 Looking forward to trying it out.

**Comment by PerfectSlayer** [comment]
The new beta is out! I'm glad I found a way to do it.
Have a look to [the announcement post](https://forum.xda-developers.com/showpost.php?p=82529473&postcount=14758) and don't forget to install the certificate if you need it.

I'm closing the issue but feel free to add more comment if you think it can be improved.
