### ISSUE TITLE
AdAway 4.0.9 showing "update" message even though the hosts have been updated

### ISSUE THREAD

**Issue by MarcAnt01** [AdAway/AdAway#1069]
OnePlus 3 Android 8.1 , AOSP base ROM

**Comment by PerfectSlayer** [comment]
Fixed in  10a9ae65d3cbfa021a34eb27e05e66e162890906

**Comment by MarcAnt01** [comment]
Thank you

**Comment by PerfectSlayer** [comment]
It was related to #1068 
When a hosts source is not valid, its last update time was null.
Then when you update your system hosts file, it uses the last update time as install time, so null to.
So when you check again if there is update, it finds the not valid hosts source as not installed (as it has a null install time) and tell you need to update it (in order to install this source).

The fix uses the current time (now) is install time so no more null values.
