### ISSUE TITLE
Don't exit AdAway when phone is not rooted, it can still be useful

### ISSUE THREAD

**Issue by charlieman** [AdAway/AdAway#1078]
I have a phone for which I can't use root (some other app needed in this phone detects root and doesn't work). So I was thinking in using AdAway to generate a hosts file somewhere else and then import it into NetGuard or DNS66 which I can use without root.

But AdAway shows a warning message and gives me only the option to exit when the phone is not rooted. In that case AdAway can still be useful to generate hosts files so it would be nice if it had an option to dismiss the message without exiting.

**Comment by Kronopt** [comment]
Adaway, basically, downloads and aggregates hosts from the sources you provide into a single hosts file. Although it only needs root to alter your hosts file, it wouldn't make much sense to create a hosts file and then just give it to you without it having any effect, so that's why that's not a feature (I presume).

If you just want to download a hosts file, you can do so [here](https://github.com/StevenBlack/hosts)

**Comment by Kronopt** [comment]
As for the having "non-detectable" root, you could check out [Magisk ](https://github.com/topjohnwu/Magisk)systemless root

**Comment by PerfectSlayer** [comment]
Hi @charlieman !

As said @Kronopt, there is no real logic to allow user to use AdAway without root.
It could even be worst if user starts discovering and spends time to configure it then finally get blocked because it is not rooted.
For your information, root is not only used to copy hosts file but also to run web server on reserved port (80) and listen to DNS request using tcpdump.

I leave the issue open for some days to discuss about it.
If no more answer, I will close it as "wontfix" 😅 

Regards.

**Comment by charlieman** [comment]
Hi.
That sounds reasonable. The hosts file from StevenBlack looks like what I need. And I'll check about Magisk. You can close this issue.

**Comment by PerfectSlayer** [comment]
You're welcome.
