### ISSUE TITLE
Lower part of letter "g" is not visible

### ISSUE THREAD

**Issue by Sopor-** [AdAway/AdAway#1096]
No big deal but as you can see in the picture the letter "g" will be cut off.

![image](https://user-images.githubusercontent.com/5789283/50665051-85ccdd80-0faf-11e9-8fe4-960761aa04db.png)

**Comment by PerfectSlayer** [comment]
Thanks for the report!
I checked on my device and I never noticed it.

I'll try to find how to tweak the layout.

---

EDIT: I found the issue. It is the only `TextView` in `home_fragment.xml` with a fixed height instead of `wrap_content`. Nice catch 😉 
https://github.com/AdAway/AdAway/blob/02f61307bd3d9b024e594691e230908872c73a8b/app/src/main/res/layout/home_fragment.xml#L228
