### ISSUE TITLE
[Feature Request] Trim hosts file

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [AdAway/AdAway#1107]
I use Steven Black's hosts file beside the hosts files from hpHosts. Also I have enabled IPv6 support. This give me a really huge hosts file (~40MB) were a lot of entries should be double. Also this hosts file is to big for the systemless support of Magisk. Therefor it would be nice, if AdAway trim the file (remove duplicates). Also this should speed up a bit the reading of the file/reduce the memory the file needs.

**Comment by Vankog** [comment]
As far as I know, AdAway already takes care of duplicates.

**Comment by PerfectSlayer** [comment]
I confirm. Duplicate entries are removed.

In fact, they are all handled in memory in order to trim them and apply user lists (black, white and redirect).

About resizing img file for Magisk, I might implement it if I drop other root support.
Otherwise it will be too much complicated to implement it with all root solutions.

**Comment by Tobias-B-Besemer** [comment]
It was a bug in Magisk! In version 4.10 (Magisk) are problems with writing -> Therefor I got a error msg.
Solved in latest nightly of Magisk...

**Comment by PerfectSlayer** [comment]
Good!
So I could close the issue 😄
