### ISSUE TITLE
twitch adblock possible?

### ISSUE THREAD

**Issue by daveimagery** [AdAway/AdAway#1132]
Was wondering if it would be possible to create a filter for the twitch.tv app.  Thank you for all your work.

**Comment by AnXh3L0** [comment]
Hi @daveimagery,

From my limited knowledge, Twitch loads ads from the same domain where the content comes from, so a host-based adblocker won't work because it would block the content too instead of just the ads.

For that, you have to use a DNS-based adblocker or find another solution for an ad-free Twitch app. A good one I personally use is https://f-droid.org/en/packages/com.perflyst.twire/
