### ISSUE TITLE
The buttons moves depending on how many chars they have

### ISSUE THREAD

**Issue by Sopor** [AdAway/AdAway#1175]
This new Adaway layout makes the `CHECK FOR UPDATES` and `DISABLE AD-BLOCKING` fit on one row so it will move around the buttons when the button change name to `UPDATE HOSTS`. Quite annoying when the button move around depending on the text in the button. The resolution i'm running is 1440x2960 with normal font size.

![image](https://user-images.githubusercontent.com/5789283/57741187-dec62400-76bb-11e9-9ea1-304f36b944fd.png)

![image](https://user-images.githubusercontent.com/5789283/57741194-e7b6f580-76bb-11e9-906a-19965e68b248.png)

## This is how it was in earlier versions:

![image](https://user-images.githubusercontent.com/5789283/57741302-8ba0a100-76bc-11e9-857e-5b0767041592.png)

**Comment by PerfectSlayer** [comment]
Hello @Sopor 

It is the expected behavior.
On the previous versions, the text was cropped or button text went on several lines (which makes the buttons square and ugly).
As I don't control the text length (it comes from translators), it is the best behavior I can make.

If you have a better idea, tell me! 😄 
Otherwise, thanks for the report and I will let you close the issue.

**Comment by Sopor** [comment]
I should prefer the buttons was like in the first picture all the time. It is the moving that is so annoying. It must be easier for the translators too. It will make the two buttons to include a lot of chars without moving around depending on the length of the words.

**Comment by PerfectSlayer** [comment]
It's again the Android Material Design/Theming guidelines: https://material.io/design/components/cards.html#actions
Actually, it is more an issue with the design of the app: the action should be simpler to understand and button text should only be a verb.
I think I will leave it as it is until the next UI.
