### ISSUE TITLE
Unable to find whitelist 

### ISSUE THREAD

**Issue by Trace27** [AdAway/AdAway#1469]
I am trying to whitelist an app. However I am unable to figure out what to add to whitelist.

The app in question is evil apples.

**Comment by Kronopt** [comment]
Well, you can't add an app to the whitelist pers se.
The best you can do (with AdAway, anyway) is figure out which **domains** the app connects to and **whitelist those domains**.

To do that:
* First disable ad-blocking in AdAway.
* Then enable DNS logging with AdAway ("Log DNS requests" option in AdAway).
* Open the app you wish to "whitelist" and play around with for a little while or let it run in the background or do whatever you're supposed to do with the app. This way it will connect to the domains it needs in order to work, which will then show up in the dns requests log.
* You can then whitelist those domains and re-enable ad-blocking.

**Comment by Trace27** [comment]
Unfortunately when I try this there are no logs recorded. I may not have it running enough. How long should it take? 

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 7, 2019 at 6:46 PM, Kronopt<notifications@github.com> wrote:   
Well, you can't add an app to the whitelist pers se.
The best you can do (with AdAway, anyway) is figure out which domains the app connects to and whitelist those domains.

To do that:
   
   - First disable ad-blocking in AdAway.
   - Then enable DNS logging with AdAway ("Log DNS requests" option in AdAway).
   - Open the app you wish to "whitelist" and play around with for a little while or let it run in the background or do whatever you're supposed to do with the app. This way it will connect to the domains it needs in order to work, which will then show up in the dns requests log.
   - You can then whitelist those domains and re-enable ad-blocking.

**Comment by Vankog** [comment]
If you are on Android 9+, this feature is not working any more, due to encryption of the traffic:
#1230

**Comment by Kronopt** [comment]
On Android 9+ I think you can disable the private DNS feature temporarily.
You can do it just while logging the domains the app connects to, and then re-enable it.

**Comment by Trace27** [comment]
Nevermind. I found it. It was already off
