### ISSUE TITLE
F-Droid metadata at the wrong place

### ISSUE THREAD

**Issue by linsui** [AdAway/AdAway#1509]
**Describe the bug**
F-Droid metadata is at the wrong place. It should be `fastlane/metadata/android/<language>/*` . See https://gitlab.com/fdroid/fdroiddata/issues/1894#note_266947972 Please fix it so that F-Droid can capture metadata from this repo. The metadata in F-Droid is out of date. Thanks!

**Comment by PerfectSlayer** [comment]
Hi @linsui 

First, thanks for the bug report!
I would prefer to use the `metadata/<lang>` path rather than the fastlane one (`fastlane/metadata/android/<lang>`) as it seems more tool agnostic.

But before removing the `android` level, I need to ask to @Vankog what are the consequences about translations on trasifex? I guess I will need to update the `.tx/config` to update the `file_filter` but will it keep translators current work?

If it is okay with him, I do the update right after!

**Comment by Vankog** [comment]
If I'm not mistaken a simple move should be just fine.
As long as the slug (aka ID) of the resource does not change and the URL for auto update gets updated.

**Comment by linsui** [comment]
Thanks!

**Comment by PerfectSlayer** [comment]
Thanks @Vankog for your advice.

I update the path, update the `.tx/confix` and the Transifex GitHub integration configuration.
I hove nothing was broken with translation platform. Please tell me if you see anything.

And thanks @linsui for letting us now about this issue! 👍
