### ISSUE TITLE
Malicious website

### ISSUE THREAD

**Issue by johnpatrick9** [AdAway/AdAway#1575]
Hello,my av(Kaspersky) is blocking your website by showing that it's a malicious website,would anyone mind helping me out please?

**Comment by PerfectSlayer** [comment]
Hello @johnpatrick9 

That is surprising. I don't really see what could be malicious about the website.
It is open source and you could check its source from here: https://github.com/AdAway/adaway.github.io

I would recommend to add the site to your AV whitelist or if you just want to download the app, use F-Droid instead https://f-droid.org/en/packages/org.adaway/

Thanks to close the issue if it helps and you don't have more questions.

**Comment by johnpatrick9** [comment]
yes I know it and brought it up with my av's support and this what they said to me 
"**We've just received a reply from our Virus Analysts with the latest update.

Based on their checking on the URL : https://adaway.org/hosts.txt
They have concluded that this is not a phishing false positive issue. The managed to find a malicious code on the website.**" so could you please ask them why they have added your site as malicious @PerfectSlayer

**Comment by PerfectSlayer** [comment]
I guess our hosts.txt file links to some domains used by virus or spam.
That is why such domains are here, to be blocked by AdAway app...

It is like if you try to ban antivirus because it has a virus database in it.
May be they should spend at least 30 seconds on the site to check what it is and state it as false positive.
