### ISSUE TITLE
crowdcast.io compatibility report

### ISSUE THREAD

**Issue by frosas** [AdAway/AdAway#1621]
**Describe the third party app**
 - Name: https://www.crowdcast.io/
 - Version: N/A

**Describe the compatibility issue**
I noticed some pages in https://www.crowdcast.io don't work (eg https://www.crowdcast.io/e/the-legacy-of-socrates/) when the default blocklist is enabled.

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
- s-usc1c-nss-262.firebaseio.com
- firebaseio.com (probably needed to solve other similar cases)

~~Please add tag `workaround-available` if a work around is available.~~ Can't do it.

**Comment by johnozbay** [comment]
Hey there @frosas! ✌🏻 
That makes two of us ( + thousands more ). This is a massive one. 

Hi everyone! 👋🏻
This domain is a general domain used by all Firebase platform customers.
Firebase dynamically moves platform customers between subdomains to handle scaling.
Here's an official explanation from a Firebase staff member on their forums ([source](https://groups.google.com/forum/#!msg/firebase-talk/SlCsde0zxQM/dszRNGD4BgAJ)) :

Q:
> ... Would the service the clients connect to behind the scenes s-usc1c-nss-122.firebaseio.com be constant for a database "projectXYZ.firebaseio.com" or is this subject to change as well?

Staff Answer:
> It is subject to change. You can be moved to a different server (the nss-### part of that URL) at any point and shouldn't rely on that for anything.

This week my service/app [Cryptee](https://crypt.ee/), an [open-source](https://github.com/cryptee/web-client) on-device encrypted, privacy advocating, productivity tools service, which relies on Firebase (for things like websockets as a part of our real-time productivity tools, as well as fallback for censorship circumvention), got moved onto the `s-usc1c-nss-262.firebaseio.com` server to handle the load. And now we're receiving complaints from users that they can't access our platform. 

Equally importantly, having this domain blocked also means, thousands of other Firebase clients are (or will be) impacted by this as well, some of which include : [NYTimes Interactive](https://twitter.com/NYTInteractive/status/989224554269741057), [HackerNews API](https://github.com/HackerNews/API), occasionally [Mozilla Firefox](https://support.mozilla.org/en-US/kb/how-do-you-use-google-firebase-firefox) itself and companies like NPR News, Lyft, Shazam, and more according to some quick search on the internet.

I've already filed a very lengthy bug report on StevenBlack's hosts list – linking here so you can read more about this issue over there as well. This is a bigger problem than just a single service, it's thousands of services. For future, if possible keep an eye out for all domains following the same `-nss-###.firebaseio.com` pattern – since all these are shared across a pool of thousands and thousands of firebase customers. 

Hoping this helps ✌🏻

**Comment by johnozbay** [comment]
Seems like the same thing's happening to [RoamResearch](roamresearch.com) and [users have been talking about it on their reddit](https://www.reddit.com/r/RoamResearch/comments/fu9dao/cant_sign_in/).

**Comment by johnozbay** [comment]
Pinging @jawz101 here as well, since it's related –

**Comment by llacb47** [comment]
Wrong repo, should be moved to https://github.com/AdAway/adaway.github.io

**Comment by johnozbay** [comment]
Sounds good! Apologies! 😩
Figured I'll link and tie things up so no knot would be left untied. 

I'll hold-off filing for another one over there, and save jawz101 an extra notification, since I've already pinged both here and on StevenBlack's thread ✌🏻

**Comment by jawz101** [comment]
please close.  thank you

**Comment by frosas** [comment]
Thanks @jawz101

**Comment by jawz101** [comment]
yw
