### ISSUE TITLE
Feature request: allow redirection for only some sources

### ISSUE THREAD

**Issue by RenaKunisaki** [AdAway/AdAway#1908]
The option to allow redirect entries is global. I wish it could apply to only specific sources, so that I don't have to worry about the security risk from other sources.

**Comment by PerfectSlayer** [comment]
Hello @RenaKunisaki 

I thought about it too because it clutters the settings UI and lakes granularity.
I plan to make an overall improvement of the source UI with more information about each source:

- Size of the file,
- Number of blocked, allowed and redirected
- Some description

Why not add the controls here?
But right now, I'm focused on fixing bugs of already shipped features 😅

**Comment by PerfectSlayer** [comment]
This feature is released in the current beta 🎉
