### ISSUE TITLE
Create ability to import/export individual lists (white/black/redirect)

### ISSUE THREAD

**Issue by mickrussom** [AdAway/AdAway#1944]
**Describe the bug**
Create ability to import/export individual lists (white/black/redirect)

Have the import / export be compatible with both json and the old format which was of the form
white *.domain1.com
white ads.domain2.com

do better error handling of badly formatted lists and json - currently failures are completely silent and if any error happens with the json format the entire operation fails. 

**To Reproduce**
NA

**Expected behavior**
- Ability to import export individual lists
- have simple and json formats supported for these lists
- do better error handling of badly formatted lists and json 

**Screenshots**
NA

**Device**
 - AdAway version: [4.3.4]
 - Device: [Pixel 3xl]
 - Android version: [10]
 - Root version [Magisk 20.4]

**Additional context**
NA

**Comment by PerfectSlayer** [comment]
Hello @mickrussom 

I won't bring old format support in the app as it does not provide all the information I need.
If you need to import an old format, you can convert it from the official site: https://adaway.org/export

Thanks to your issue, I noticed an error in the toast to display import failure.
It will be fixed in the next beta 👍 

Regards
