### ISSUE TITLE
hosts sources "need update" negative time

### ISSUE THREAD

**Issue by daemoncrafter** [AdAway/AdAway#2052]
great app.  it knows the future 🙂

![Screenshot_20200521-073225](https://user-images.githubusercontent.com/29263834/82557221-546b9800-9b39-11ea-8b34-bd09308c3fc0.png)

version 4.3.4 running on pie.

**Comment by JonnyTech** [comment]
Is the time set on your device correctly?

**Comment by crok** [comment]
First of all If I were you I would check the [release page](https://github.com/AdAway/AdAway/releases), the latest version is [5.0.3](https://github.com/AdAway/AdAway/releases/tag/v5.0.3b) and [this issue you've mentioned](https://github.com/AdAway/AdAway/issues/1800#issuecomment-620117447) has probably been already reported in issue #1800 more than a month ago and the fix is probably already ready [(and here's the explanation)](https://github.com/AdAway/AdAway/issues/1800#issuecomment-623055137) and [the issue has been moved to development phase 11 days ago](https://github.com/AdAway/AdAway/issues/1800#event-3320171116) so the fix is already on the way I guess (:

**Comment by daemoncrafter** [comment]
it's viewing correctly in my status bar & running 'date' in termux returns the appropriate date / time.

![Screenshot_20200521-103254](https://user-images.githubusercontent.com/29263834/82569634-820f0c00-9b4e-11ea-80cc-373aead58c69.png)

**Comment by daemoncrafter** [comment]
as per crok above the latest 5.0.3b does list a possible fix for this issue.
I'll update to the lasted beta & recheck.

"Add workaround for negative source update time when server time is not accurate"

**Comment by ipdev99** [comment]
The above circled host source _https://pgl.yoyo.org_ was fixed this morning on their side.
_It was an issue with a code update, and the edit/change was missed in some of his scripts._
It is now proper GMT.

Unless you have another source that shows the wrong time.
There is no work-a-round needed and this issue can be closed.

**Comment by daemoncrafter** [comment]
the offending host source (pgl.yoyo.org) has been fixed.
