### ISSUE TITLE
Sonic App Crashing

### ISSUE THREAD

**Issue by pewnflap** [AdAway/AdAway#2103]
I'm using the default HOSTS repositories, Sonic Drive-In app is crashing upon checkout or adding payment methods.

It will function properly with Ad-away disabled. 

Not sure if this is the correct place to post.

**Comment by PerfectSlayer** [comment]
Hello @pewnflap 

It may worth it to try to log the request and find which domain is required to get the app working.
See here how to do it: https://github.com/AdAway/AdAway/wiki/LogDNS

**Comment by pewnflap** [comment]
I followed the directions in the link and whitelisted every hostname that came up over multiple attempts. Even restarted. The app still crashes in the same. Thanks for the help.

**Comment by bengalih** [comment]
Ah,... I love it.  I'm able to help someone out here and discuss my problem without opening a new issue (yet)!
@jawz101 recommended I bring this to the attention of @PerfectSlayer after discussing this problem in the StevenBlack host repo here:

https://github.com/StevenBlack/hosts/issues/1345#issuecomment-663855374

To fix the OP issue, he needs to whitelist *.split.io
But there is a more pressing issue with the app (beyond the fact that I believe keeping split.io on the main blacklist is not warranted).
The issue is exactly what the OP is saying is that split.io does NOT show up as hit in the DNS logging unless you DISABLE host blocking.
So, there is definitely some weirdness going on in how the app shows DNS hits when blocking is disabled vs. enabled.
Additionally, I have some ideas for streamlining the diagnosing of issues like (finding which site is blocking) which I should like to discuss if @PerfectSlayer is open to some enhancements.
