### ISSUE TITLE
Can't install CA certificate on Android 11

### ISSUE THREAD

**Issue by ingenium13** [AdAway/AdAway#2245]
With AdAway 5.0.9 and Android 11, there is no way to install the CA certificate. Attempting to do so display an error: "Install CA certificates in Settings. This certificate from null must be installed in Settings. Only install CA certificates from organizations you trust."
![Screenshot_20201009-120801](https://user-images.githubusercontent.com/3280458/95606508-6c7c7f00-0a28-11eb-8eda-19c0b6cbb4dc.png)

I can't find a certificate anywhere on internal storage, so I can't add it manually in Settings.

**Comment by PerfectSlayer** [comment]
Hello @ingenium13 

Thanks for bringing this issue to me.
I don't have a physical device to test root ad-block on Android 11 so I didn't notice it.

From the documentation: https://developer.android.com/work/versions/android-11#other
![image](https://user-images.githubusercontent.com/1766222/95657314-2e5c8980-0b14-11eb-881f-e796cdf12c57.png)

I think I will:
* Check Android version first
* If Android 10 or less, keep the current behavior
* Otherwise:
  * Ask to the user where to copy the certificate (DocumentUI)
  * Copy the certificate to user storage
  * Show a dialog to user to explain how to install certificate from settings.

Not very user friendly... But I don't think I can do better 😞

**Comment by PerfectSlayer** [comment]
The result is really not user friendly but I don't think I can do better... 🤷‍♂️ 

Here is what is shown when clicking the "install self-signed certificate" settings in Android 11:
![Screenshot_1602343902](https://user-images.githubusercontent.com/1766222/95658991-9fa13a00-0b1e-11eb-8686-6cc2a3036ef2.png)
Then I notify the user about Android 11 situation and explain it how to install it manually
![Screenshot_1602343907](https://user-images.githubusercontent.com/1766222/95658993-a16afd80-0b1e-11eb-944c-9e0675d768b6.png)
Then I bring it to the Security settings screen (the closest I can from manually installing the CA)
![Screenshot_1602343911](https://user-images.githubusercontent.com/1766222/95658994-a334c100-0b1e-11eb-8d19-f1315de3b404.png)

Thanks 🙏
