### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [AdAway/AdAway#2429]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by PerfectSlayer** [comment]
Hello,

There already are screenshots on F-Droid: https://f-droid.org/en/packages/org.adaway/
Don't you see them ?

**Comment by m-rey** [comment]
The official F-Droid app sometimes just doesn't show the screenshots. I have noticed it myself, but I wasn't able to consistently reproduce it yet.
In my case, it also happens when displaying the information page of other apps.

The AdAway detail page on web version of F-Droid displays the screenshots just fine: https://f-droid.org/en/packages/org.adaway/

**Comment by PerfectSlayer** [comment]
Thanks for the information! I was lost understanding the issue as I don't use the F-Droid store application.

I thinks the issue comes from the F-Droid store so... Do you agree?

**Comment by mondlicht-und-sterne** [comment]
It's showing some now, thanks. Then I'll close here now.
