### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by bdtipsntricks** [AdAway/AdAway#2433]
**Describe the bug**
update available but can't update the app.

**Expected behavior**
Should install new version smoothly

**Screenshots**
![Screenshot_20210106-161649](https://user-images.githubusercontent.com/6330712/103757179-9a2e8f80-503a-11eb-8f53-d2ffc0aee9f4.jpg)
![Screenshot_20210106-161453](https://user-images.githubusercontent.com/6330712/103757194-9c90e980-503a-11eb-98c7-39c18e472a5e.jpg)

**Device**
 - AdAway version: 5.1.0
 - Device: OnePlus 8T (India)
 - Android version: 11
 - Root version: Magisk 20.4

**Comment by faraz-b** [comment]
Getting the same issue here.

AdAway version: 5.1.0
Device: OnePlus 5
Android version: 10 (Oxygen OS 10.0.0)
Root version: Magisk 20.4

**Comment by bege10** [comment]
Same here. The reason is that I have installed Adaway from F-droid and Adaway tries to update with the version from github. As far as I found out this is not possible. I uninstalled the F-droid version and installed the github version. Now the update works.

I think the option to update the app should be removed from the F-droid version.

**Comment by PerfectSlayer** [comment]
Hi all,

The built-in updater is able to update GitHub and F-Droid version so it should not be removed.
There is well a bug in the _store_ detection (GitHub or F-Droid) which makes the app proposes GitHub update on F-Droid releases... 
As mentioned, I describe the issue on #2428 and it should be fixed in the coming 5.2.1 release.

Regards
