### ISSUE TITLE
Outdated version on f-droid

### ISSUE THREAD

**Issue by reconman** [AdAway/AdAway#2439]
**Describe the bug**
F-droid still lists 5.1.0 as latest version instead of 5.2.1.

**Expected behavior**
5.2.1 should be available.

**Comment by PerfectSlayer** [comment]
Hello everyone,

Thanks for the report, we started discussing the issue here: #2428
I can't control the build environment on F-Droid and I can't trigger a new build on demand (I need to publish a new version each time...). For now, the available SDK on F-Droid build server seems outdated and can't build AdAway.

It is in the hands on F-Droid team.

Regards

**Comment by derN3rd** [comment]
@reconman the build isjow available on F-Droid

**Comment by reconman** [comment]
@derN3rd Thanks
