### ISSUE TITLE
The allowed urls doesn't show anything but stays blank

### ISSUE THREAD

**Issue by milindgoel15** [AdAway/AdAway#2617]
**Describe the bug**
When seeing the allowed URLs, it gives a blank page. Attaching screenshot here of this issue. 

**To Reproduce**
1. Open adaway
2. Tap on allowed lists
3. It gives blank page

**Expected behavior**
If an user has allowed some urls to allowed list, it should display.

**Screenshots**
![Screenshot_20210317-230118180.jpg](https://user-images.githubusercontent.com/45682747/111511832-1b11b200-8775-11eb-838e-062920ccef6c.jpg)
![15824.png](https://user-images.githubusercontent.com/45682747/111511886-27960a80-8775-11eb-9fe8-97c9a7a90fc0.png)

**Device**
 - AdAway version: 5.5.0
 - Device: Nokia 6.1
 - ROM: EvolutionX
 - Android version: Android 10
 - Root version: Magisk 21.4

**Additional context**
Don't think this needs any logcat. But if you require it, please tell me and I will send. The issue persisted in old version too(5.4.0 and 5.3.0 too iirc).

Also, please ignore my theme as I use substratum themes xD.

**Comment by zgfg** [comment]
With AdAway 5.4.0 and earlier I had Allowed URLs manually defined and everything worked perfect.
It also worked with 5.5.0 when I updated 

Since 5.5.0 supports Allowed list, I changed from allowed list file instead of defining them one by one, and it also works fine for me

![IMG_20210318_062223](https://user-images.githubusercontent.com/51943147/111578288-26d09900-87b4-11eb-99bd-741574f8f0c4.jpg)
![IMG_20210318_062028](https://user-images.githubusercontent.com/51943147/111578297-2cc67a00-87b4-11eb-9b5d-9a75b28a8dfe.jpg)


Xiaomi Mi 9T, Magisk 22005

But up to few months ago I also had not rooted Huawei Mate 9, running Adaway 5.x.x versions in VPN mode, and Allowed sites (manually defined) also worked fine

Hence not sure what is wrong on your side, i.e. how you got in that state

I would suggest you to Clear data for AdAway from Settings, Apps and to configure your AdAway again

**Comment by milindgoel15** [comment]
Ok sure. I just flashed my ROM again(cuz actually I was testing a11 and some issue came up with it) and will check freshly.

**Comment by milindgoel15** [comment]
Update on the issue:

It's fine after fresh installation. I can think of only 1 reason why this issue happened to me as I added more hosts to completely block ads on my device hence the app wasn't able to display. I will check to reproduce this again later and will post here.

**Comment by zgfg** [comment]
If it works, you can close the issue

**Comment by milindgoel15** [comment]
I will, don't worry.
