### ISSUE TITLE
Adaway Not Able to Block Ads

### ISSUE THREAD

**Issue by prorounak2005** [AdAway/AdAway#2823]
I am using a vpn adblocker in adaway but there are still lot of ads in youtube and in built application like play store , chrome , google still have ads. Adaway is able to block ads on applications which are not inbuilt. I don't know how to root my device because the steps are hard. Please help.

**Comment by rjbweb** [comment]
Redmi Note 9S Global
Hi there, similar issue but not working on any app.
I have a Redmi Note 9s and since the last update to MIUI 12.0.2.0 RJWEUX, Adaway has stop to block any ads at all in apps or browser, I use Edge as a browser and I don't use data saver.
I tried to uninstall and reinstall but nothing works... It was ok few days ago but since the update... nothing works...
My 9s isn't rooted I use Adaway as VPN.
Thanks in advance.

**Comment by prorounak2005** [comment]
Having the same problem. Can anyone help us?
