### ISSUE TITLE
Dns won't work

### ISSUE THREAD

**Issue by NSTAdventure** [AdAway/AdAway#2921]
**Describe the bug**
I excluded dns (allow) and yep still not able fo connect via dns (it's dns over TLS)

**To Reproduce**
1. Open Adaway add specific dns over tls web to whitelist or allow them
2. Now try to enable dns from oem setting and you still can't connect

**Expected behavior**
You still able to use dns over TLS

**Screenshots**
![Screenshot_2021-09-22-18-06-49-08](https://user-images.githubusercontent.com/50813528/134441406-8158274d-09da-47ca-ad41-af6d82f7aa3f.jpg)

![Screenshot_2021-09-23-08-11-30-60](https://user-images.githubusercontent.com/50813528/134441541-69058c76-426e-4577-9c6d-afa7225cabd4.jpg)
(Language ID) cannot connect to dns disable dns to use wifi -_-

**Device**
 - AdAway version: 5.8.0
 - Device: Realme 5i
 - Android version: 10
 - Root version: non root (VPN)

**Additional context**

**Comment by sereksim** [comment]
AdAway seems to interfere with the private DNS on Android, so you can't use both at the same time...
I've got the same problem: 

**Current Behaviour**
In vpn mode, AdAway blocks the private DNS server option. It is not possible to have a functioning internet connection if both AdAway and a private DNS server are enabled at the same time.

**Expected Behaviour**
AdAway should not interfere with the private DNS server and shoud work anyways.

**Steps to Reproduce**
- Go your phones settings -> search for dns -> private dns -> choose a private dns e.g. dns3.digitalcourage.de
- Turn AdAway on
- DNS does not resolve -> Android Error message "Network has no internet access - private dns server is not reachable"

**Device Configuration**
- AdAway version: 6.0.3 
- Ad-blocker mode: VPN
- Device: Xiaomi Mi 9T Pro
- Android version: MIUI 12.5 | V12.5.6.0.RFKCNXM | (stable)  -  Android-Version: 11RKQ1.100826.002
- Root version: no root

**Comment by NSTAdventure** [comment]
After few investigation it's looks like this behavior occur due to android limitations that usually developer unable to do anything with it

Closed

**Comment by sereksim** [comment]
@ghost There are dns apps which work absolutely fine without this problem, so I don't see why AdAway shouldn't be able to solve this too
