### ISSUE TITLE
[Feature Request] Re-add symlinked hosts file support

### ISSUE THREAD

**Issue by samolego** [AdAway/AdAway#3192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First of all, great app!
In older versions of adaway, it was possible to point adaway to the custom hosts file (e.g. on user storage, where app has write permissions), to which `/system/etc/hosts` pointed. In "modern" versions, that's no longer possible.

### Expected Behavior

Being able to specify a custom hosts file would be nice :).

### Device Configuration

- AdAway version: 5.12.0
- Ad-blocker mode: no root but not vpn as well :)

**Comment by PerfectSlayer** [comment]
Hi,

So you basically using AdAway to download and merge hosts file but you don't want it to install the hosts file in your system? (like installing it using recovery script or consumed by another app?)

There was some discussions about it for a _light_ version of AdAway that only handle hosts (no root, no vpn, no dns logs, etc...) but it never happens.
And I don't think adding it the current app makes sense because user will want to use it without rooting their devices and the setup page will require it. It will be too confusing.

To me, the easiest thing to achieve this is to fork the app, remove all features you don't want and brand it like an hosts file merger. I don't think I will be able to make it as I already have a lot on my plate to maintain the current features 😅 

Is it related to #2474 ?

**Comment by samolego** [comment]
Yeah, you got it right, basically hosts "manager". Kinda like #2474 without the flashing part (so it's even easier).

Since all the functionality is already there, I've forked the project and removed some checks things to get it working, however, I can't really say I have enough experience to develop the app any further :).

**Comment by PerfectSlayer** [comment]
If it suits your needs, that is enough!
The installation part should be located in the `RootModel` class. Just remove what you don't need and create the file where you need it 😉
