### ISSUE TITLE
zero hosts listed for successfully synced sources

### ISSUE THREAD

**Issue by wastemans** [AdAway/AdAway#3434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adaway will fetch my host sources without complaint, but with 31 sources, there aren't enough blocked hosts, and in the sources list, most of the sources have zero hosts.

### Expected Behavior

Display hosts fetched (or at least "0 hosts") for sources adaway has fetched.

### Steps To Reproduce

You can use my JSON file and just sync to see if it works for you.

https://gist.github.com/wastemans/63eddc6748dade82f7930267c55dc579

Just import the backup and sync it.

[I sourced all the safe/blue entries from this site](https://firebog.net/) 

### Device Configuration

- AdAway version: 603
- Ad-blocker mode: root
- Device: Asus ZenFone 7
- Android version: 12.1
- Root version: magisk 25.2

**Comment by wastemans** [comment]
![Screenshot_20230119-093043](https://user-images.githubusercontent.com/106939693/213406179-fd14e245-5465-4a0a-9464-b6c1e7406b31.png)
Screenshot for better clarity...some of these host sources are the same built-in sources that come with program...

**Comment by wastemans** [comment]
Incidentally, I also have this list as a CSV if anyone wants an earlier to manage, more portable sources list.

**Comment by gallegonovato** [comment]
Good afternoon:

From the link https://gist.github.com/wastemans/63eddc6748dade82f7930267c55dc579 it will work for you:

https://adaway.org//hosts.txt

https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

https://pgl.yoyo.org//adservers//serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

https://pgl.yoyo.org//adservers//serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext (This one is repeated)

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt

https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt



This one may give you problems because Adaway may not know when it is updated. 

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts

It is very small:

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts (It can cause the same problem as the previous one)

These will not work because it does not have 0.0.0.0.0 or 127.0.0.1:

https://v.firebog.net//hosts//static//w3kbl.txt

https://v.firebog.net//hosts//AdguardDNS.txt

https://v.firebog.net//hosts//Admiral.txt

https://v.firebog.net//hosts//Easylist.txt

https://v.firebog.net//hosts//Easyprivacy.txt

You have two Adaway sources. But Adaway already includes it, so you can remove the Adaway ones from https://gist.github.com/wastemans/63eddc6748dade82f7930267c55dc579.

The same is true of the others that are missing. If they don't have 0.0.0.0.0 or 127.0.0.1 Adaway doesn't recognize them as hosts.

So you can remove them. The same with https://firebog.net/

You have a lot of hosts at https://filterlists.com/

And so on https://github.com/hagezi/dns-blocklists , https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts , then there were the energized ones but I don't think they are there anymore. 

A hug

**Comment by wastemans** [comment]
Thanks @gallegonovato 
Will close and look at filterlists for a better solution.

**Comment by gallegonovato** [comment]
Good afternoon @wastemans

No need to say thank you. We are here to help :)

Check that they have 0.0.0.0.0 or 127.0.0.1 in front of each thing to block.

There are more in gitlab or Codeberg for example. But it all depends on what you want to block. But filterlist can help you. If you allow me one more tip, check that the source is updated. Because there are some that have not been updated for years and maybe the things you block do not exist.

Best regards
