### ISSUE TITLE
Can't Add Default Hosts Source

### ISSUE THREAD

**Issue by Timecrash** [AdAway/AdAway#3452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I downloaded the AdAway 6.0.3 APK off GitHub, installed it, and saw only Pete Lowe's and Steven Black's hostfiles as sources. I tried adding the AdAway source (`https://adaway.org/hosts.txt`), however it takes me back to the `Hosts sources` screen with no change and no indication it's doing anything.

### Expected Behavior

AdAway displays a message saying it's downloading the hostfile, then adds it to the source list.

### Steps To Reproduce

1. Download 6.0.3 APK from GitHub and install.
2. Open the app.
3. Select the Hosts panel.
4. Click the + to add a source.
5. Add any source (`https://adaway.org/hosts.txt`) with appropriate label.
6. Click the checkmark to add the source.

### Device Configuration

- AdAway version: 6.0.3
- Ad-blocker mode: VPN
- Device: Pixel 6
- Android version: 13
- Root version: n/a

**Comment by Timecrash** [comment]
![Screenshot_20230224-134738](https://user-images.githubusercontent.com/15052506/221266047-dbf4c016-e445-436b-8334-dfa8de35dca9.png)

**Comment by Timecrash** [comment]
I found that downloading the preview build, instead of the one on the GitHub releases page, allows me to add hosts correctly.

**Comment by jmoney97** [comment]
After you add the source, is it displaying a message at the bottom in a while banner that changes have occured and you have to exit to apply?

**Comment by gallegonovato** [comment]
Good afternoon @Timecrash

The AdAway listing already comes with the application itself. Since it brings four lists of host sources. 

Adaway's, StevenBlack's, pgl's and winhelp2002's. 

As you can see at https://github.com/AdAway/AdAway/wiki/HostsSources

Try uninstalling the app, reboot the phone. And reinstall it again.

Or try adding https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt set it as Block and URL. And then adding. It should appear at the bottom apply changes. And AdAway do the processes of integration, update, create and copy the new hosts.

Or if you prefer try another one from StevenBlack from: https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants

A hug

**Comment by Timecrash** [comment]
Hi, I think this ended up being a weird problem with my phone and using the latest stable release at time of writing. The preview ended up working fine, so I can close this ticket.
