### ISSUE TITLE
Feature request: Google Ad services

### ISSUE THREAD

**Issue by james-mcguire** [AdAway/AdAway#722]
Would be nice to be able to whitelist google ads.   Often times, they have better results than google, and I'm happy to click a non-intrusive google text ad.

**Comment by mikefaille** [comment]
It think the only way community will accept your issue is by creating a switch to switch between community list (like : acceptable ads, block spam only, block trackers only, etc). For me, I don't want any Ads by default.

And, please read this : 
https://blog.stackoverflow.com/2016/02/why-stack-overflow-doesnt-care-about-ad-blockers/?cb=1
