### ISSUE TITLE
Nexus 5x - hosts file isn't working

### ISSUE THREAD

**Issue by Arinerron** [AdAway/AdAway#830]
On Android Nougat stock ROM (Nexus 5x), the system just doesn't pay attention to the hosts file. It applies fine, but just doesn't work. USB Debugging/adb enabled, rooted, ANDROID_DNS_MODE=true, and gave 777 perms.

I don't know what is going on, and I've tried several guides/posts. Can anyone help?

**Comment by 0-kaladin** [comment]
How are you rooted and what version of AdAway

**Comment by Arinerron** [comment]
adb and the latest, but afaik, I'm not entirely sure that the first one is relevant.

**Comment by 0-kaladin** [comment]
I mean SuperSU? System less?
And please post the version. What you think is latest may not be. Depends on where you got it from.

**Comment by Arinerron** [comment]
SuperSU and 3.1.2 from the official source suggested from the website (aka
https://f-droid.org/repo/org.adaway_57.apk). Thanks for helping by the way,
it's nice that finally someone's helping

**Comment by 0-kaladin** [comment]
That's an older build that will be updated this week. In the meantime look at the readme here and grab the latest build from the XDA thread. See if that helps you.
If you are system less ensure you check the box in preferences.

**Comment by 0-kaladin** [comment]
Basically, grab the 3.2 build here. 
http://forum.xda-developers.com/showthread.php?t=2190753 You will have to uninstall your current copy first.

**Comment by Arinerron** [comment]
Okay. I did that. Now the problem is that I can't check "systemless root" check box. Whenever I click it, it gets access granted from SuperSU, but then it stays unchecked and does nothing.

**Comment by 0-kaladin** [comment]
So I think on the 5x you need SuperSU to be system less so we can write the
hosts file. Unless you load a custom kernel normal root won't allow write
to system.

On Mon, Nov 21, 2016, 21:46 Arinerron <notifications@github.com> wrote:

Okay. I did that. Now the problem is that I can't check "systemless root"
check box. Whenever I click it, it gets access granted from SuperSU, but
then it stays unchecked and does nothing.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/AdAway/AdAway/issues/830#issuecomment-262132859>, or mute
the thread

**Comment by Arinerron** [comment]
I still can't enable systemless mode :(

**Comment by 0-kaladin** [comment]
You have to make sure your SuperSU is system less. AdAway just works with
that, but it isn't a root tool. Go to a nexus 5x thread on XDA to get help
with rooting system less.

**Comment by Arinerron** [comment]
​I mean, it is already rooted systemless.​ I just can't check the box in
AdAway that enables systemless mode.
