### ISSUE TITLE
Suggestion: add an option to import/export hosts sources

### ISSUE THREAD

**Issue by superlex** [AdAway/AdAway#919]
Currently there is an option to import/export blacklist and whitelist.
What about an option to import/export hosts sources?

Thanks for your work.

**Comment by PerfectSlayer** [comment]
I think about improving import / export feature of the application: remove it for your list section and move it to settings instead of adding a new import / export button.
Doing so, you could import and export whitelist, blacklist, redirection list and hosts sources at the same time.

What do you thing about it?

**Comment by DrSaad77** [comment]
@PerfectSlayer
First Thanx for your hard work!
The stuffs you enumerated would be great!! At the same time, add setting backup of the app, to the list. So that would be:
import and export for 
> whitelist & blacklist
>redirection list
> hosts sources 
> Main setting of the app itself
So One main Backup/Restore feature for the whole app 😉

**Comment by PerfectSlayer** [comment]
Hosts sources are now backed up! 🎉  
Check PR #1189 for mote details.

**Comment by superlex** [comment]
Thank you very much :)
