### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by CaptainFrosty** [AdAway/AdAway#927]
Plenty of outstanding bugs and issues, no updates. Sounds like a coder more skilled than I needs to fork a new project.

**Comment by Vankog** [comment]
There are some rather promising forks, like @PerfectSlayer's, who concentrates on the systemless implementation.
But since AdAway is a "organization" it might be better to pull such candidates in to have more maintainers. 
@dschuermann, don't you think you should add some active contributors?

**Comment by Techman-** [comment]
I thought @PerfectSlayer was already listed as a maintainer. Last time I checked, he was working on a PR to add systemless support.

**Comment by Vankog** [comment]
His PRs are in limbo for months now. Well I don't see any associations.

**Comment by PerfectSlayer** [comment]
@Vankog It's more than systemless implementation. It's true I only push PR for systemless support here but my fork is dedicated to _upgrade_ the whole application.
I started by remove the outdated and deprecated libraries (like ActionBarSherlock) and add support libraries instead. I also try to profit of the latest android features (new library for automatic update task that support new battery optimizations). Now, I'm making a global overhaul of the design to match material design.

@Techman- No, I'm not an official maintainer. You might have seen my nickname in the last changelog due to my contributions. That's all.
The good news is I'm free to make change and refresh the app as I want (no need to have council approbation to change the layout of the home screen for example) but I'm not legitimate to make an official build of the app. It's not really an issue until I finish the upgrade: it's a side project for me, I can take my time. But when I will have to polish the app and need user feedback, it could be a real issue.

I see more and more users asking for application updates and support (latest root methods and systemless lately) and I hope my fork could help to keep this project alive! 😄

**Comment by dschuermann** [comment]
@PerfectSlayer I am happy if there is any new maintainer. I just send you an invitation on Github.

For explanation: I stopped maintaining long ago. That is also why I moved everything to a github organization. Everyone who likes to help is invited to do so, I am no longer working on this. Just ping me and I add you to the org. I am also happy to give away the ownership of this Github org!

**Comment by PerfectSlayer** [comment]
Hi @dschuermann Thanks for the invitation! I just join the org.
About the ownership of the org, we need to discuss with @0-kaladin because he also seems to be greatly involved with the XDA thread.
Moreover, if you leave the project long time ago, who is running the F-droid project page, @0-kaladin too?

**Comment by dschuermann** [comment]
About F-Droid: You can simply do a pull request to https://gitlab.com/fdroid/fdroiddata . Currently the metadata on F-Droid is configured to automatically build from the latest git tag.

**Comment by dschuermann** [comment]
@PerfectSlayer I looked at your commits and just made you the owner. I am really happy if someone pushes this forward. Please write me an email at  dominik@schuermann.eu for discussion more details.

**Comment by SMed79** [comment]
Hi, 

@dschuermann How we can help[1] for the outdated [hosts.txt](https://adaway.org/hosts.txt) file which is **not** hosted at github?

_[1] removing dead/inactive/redundant domains._

**Comment by dschuermann** [comment]
It is here: https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt

You can do PRs against the repo.

**Comment by SMed79** [comment]
Thank you.

**Comment by Vankog** [comment]
Haha, congrats @PerfectSlayer. This was faster than I'd imaged this to go. ^^
I hope this was in your interest. ;-)

**Comment by PerfectSlayer** [comment]
You're welcome @Vankog ! Sure it is 😊
