### ISSUE TITLE
A request on a site

### ISSUE THREAD

**Issue by arrivalss** [AdAway/AdAway#941]
Could you block the add on this site ?
‎https://www.meleklermekani.com/forums/

**Comment by SMed79** [comment]
If you mean the [floating banner](http://i.imgur.com/C5B5ssk.png), no you can not via the [hosts](https://en.wikipedia.org/wiki/Hosts_(file)) because it's served from the 1st party site.

An alternative is to Install **[Adblock Browser](https://adblockbrowser.org/)** then add this custome filter
```
meleklermekani.com##.FloatingContainer
```

**Comment by SMed79** [comment]
If you mean the [floating banner](http://i.imgur.com/C5B5ssk.png), no you can not via the [hosts](https://en.wikipedia.org/wiki/Hosts_(file)) because it's served from the 1st party site.

An alternative is to Install **[Adblock Browser](https://adblockbrowser.org/)** then add the custome filter below

`meleklermekani.com##.FloatingContainer`
or
`||meleklermekani.com/portal/wp-content/uploads/2017/04/utucu.jpg`

**Comment by arrivalss** [comment]
Thank you very much your fast response. I understand.
