### ISSUE TITLE
Work without root?

### ISSUE THREAD

**Issue by ale5000-git** [AdAway/AdAway#980]
Can it work without root if it is installed in /system/priv-app?

If no, is it possible to add it?

**Comment by SMed79** [comment]
> Can it work without root

 Not possible without rooting your device.

As an alternative you can use [Adblock Browser](https://adblockbrowser.org/) (block ads in browser).
...or DNS adblock servers https://adguard.com/en/adguard-dns/overview.html

**Comment by SMed79** [comment]
You can also test [**DNS66**](https://github.com/julian-klode/dns66#dns-based-host-blocking-for-android) which does not require root.

> DNS66 establishes a VPN interface, and redirects DNS server traffic to it. The VPN interface filters the traffic, only allowing queries for hosts that are not blacklisted.

**Comment by JonnyTech** [comment]
I think that what @ale5000-git is asking is if someone has an unrooted device but is able to push the AdAway apk file from recovery to `/system/priv-app/` where it will run with system privileges then will it work correctly? AFAIK any app located there should behave as root since it inherits all system privileges but I am unable to test it at the moment. All it really needs to do is modify the hosts file. With Oreo the app also needs to be whitelisted, see https://source.android.com/devices/tech/config/perms-whitelist

**Comment by ale5000-git** [comment]
As @JonnyTech said there may be a perrmission allow to do it (that should be searched).

For example F-Droid Privileged Extension can install any apps without enabling unknown sources and without using root; just by using a permission granted only to apps inside /system/priv-app.

It would be nice to use AdAway without root in this way.

**Comment by PerfectSlayer** [comment]
The version 5, which is currently in beta, supports this feature 🎉

**Comment by otuva** [comment]
Putting latest stable apk under /system/priv-app doesn't work. Adaway still wants root access any ideas on how to make it work?

**Comment by Charlyo** [comment]
@ale5000-git have you found any way to do it?

**Comment by corax205** [comment]
Is this feature implemented or not?
Adaway is probably the last app on my phone that needs root.

**Comment by antrmn** [comment]
Can anyone confirm that putting adaway in /system/priv-app will work?
